name: LEIHS/v5/admin
windows:
  2:
    name: app
    command: |
      export LEIHS_ADMIN_HTTP_BASE_URL=http://localhost:3220
      lein do clean, repl
    post_command_send_keys: |
      (-main "run")
  3:
    name: figwheel
    command: |
      ./scripts/prepare-shared-ui.sh && \
      lein figwheel
  5:
    name: psql
    command: |
      psql -d leihs
  6:
    name: db
    command: |
      cd database
  7:
    name: test
    command: |
      export LEIHS_ADMIN_HTTP_BASE_URL=http://localhost:3220
      export RAILS_ENV=test
  8:
    name: log
    command: |
      mkdir -p log && echo " " > log/debug.log && tail -f log/debug.log
