jobs:
  specs:
    name: Run specs
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      generate_tasks:
        include_match: spec/.*_spec.rb
      task_defaults:
        include:
          - cider-ci/uberjar_task-component.yml
        git_options:
          submodules:
            include_match: ^.*$

